//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Negocio.WSBodega {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWs_Bodega", Namespace="http://tempuri.org/")]
    public partial class Ws_Bodega : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_GuiasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ws_Bodega() {
            this.Url = global::Negocio.Properties.Settings.Default.Negocio_WSBodega_Ws_Bodega;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_GuiasCompletedEventHandler Get_GuiasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWs_Bodega/Get_Guias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/justtime.wcf.limatco.model")]
        public Guias[] Get_Guias([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string token, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string identidad, long numero, [System.Xml.Serialization.XmlIgnoreAttribute()] bool numeroSpecified) {
            object[] results = this.Invoke("Get_Guias", new object[] {
                        token,
                        identidad,
                        numero,
                        numeroSpecified});
            return ((Guias[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_GuiasAsync(string token, string identidad, long numero, bool numeroSpecified) {
            this.Get_GuiasAsync(token, identidad, numero, numeroSpecified, null);
        }
        
        /// <remarks/>
        public void Get_GuiasAsync(string token, string identidad, long numero, bool numeroSpecified, object userState) {
            if ((this.Get_GuiasOperationCompleted == null)) {
                this.Get_GuiasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_GuiasOperationCompleted);
            }
            this.InvokeAsync("Get_Guias", new object[] {
                        token,
                        identidad,
                        numero,
                        numeroSpecified}, this.Get_GuiasOperationCompleted, userState);
        }
        
        private void OnGet_GuiasOperationCompleted(object arg) {
            if ((this.Get_GuiasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_GuiasCompleted(this, new Get_GuiasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/justtime.wcf.limatco.model")]
    public partial class Guias {
        
        private string bodegaField;
        
        private decimal cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private decimal cantidad_primariaField;
        
        private bool cantidad_primariaFieldSpecified;
        
        private decimal cantidad_secundariaField;
        
        private bool cantidad_secundariaFieldSpecified;
        
        private string codigo_tecnicoField;
        
        private string descripcion_documentoField;
        
        private string descripcion_productoField;
        
        private string docField;
        
        private string documentoField;
        
        private System.DateTime fecha_emisionField;
        
        private bool fecha_emisionFieldSpecified;
        
        private System.DateTime fecha_registroField;
        
        private bool fecha_registroFieldSpecified;
        
        private int idbodegaField;
        
        private bool idbodegaFieldSpecified;
        
        private long idcodigoField;
        
        private bool idcodigoFieldSpecified;
        
        private int iddocumentoField;
        
        private bool iddocumentoFieldSpecified;
        
        private string identidadField;
        
        private long idnumeroField;
        
        private bool idnumeroFieldSpecified;
        
        private string idsucursalField;
        
        private int lineaField;
        
        private bool lineaFieldSpecified;
        
        private long numeroField;
        
        private bool numeroFieldSpecified;
        
        private string razon_socialField;
        
        private decimal rtuField;
        
        private bool rtuFieldSpecified;
        
        private string simbolo_bodegaField;
        
        private string unidadField;
        
        private string unidad_primariaField;
        
        private string unidad_secundariaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bodega {
            get {
                return this.bodegaField;
            }
            set {
                this.bodegaField = value;
            }
        }
        
        /// <remarks/>
        public decimal cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal cantidad_primaria {
            get {
                return this.cantidad_primariaField;
            }
            set {
                this.cantidad_primariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidad_primariaSpecified {
            get {
                return this.cantidad_primariaFieldSpecified;
            }
            set {
                this.cantidad_primariaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal cantidad_secundaria {
            get {
                return this.cantidad_secundariaField;
            }
            set {
                this.cantidad_secundariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidad_secundariaSpecified {
            get {
                return this.cantidad_secundariaFieldSpecified;
            }
            set {
                this.cantidad_secundariaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigo_tecnico {
            get {
                return this.codigo_tecnicoField;
            }
            set {
                this.codigo_tecnicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descripcion_documento {
            get {
                return this.descripcion_documentoField;
            }
            set {
                this.descripcion_documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descripcion_producto {
            get {
                return this.descripcion_productoField;
            }
            set {
                this.descripcion_productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fecha_emision {
            get {
                return this.fecha_emisionField;
            }
            set {
                this.fecha_emisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_emisionSpecified {
            get {
                return this.fecha_emisionFieldSpecified;
            }
            set {
                this.fecha_emisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                this.fecha_registroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_registroSpecified {
            get {
                return this.fecha_registroFieldSpecified;
            }
            set {
                this.fecha_registroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int idbodega {
            get {
                return this.idbodegaField;
            }
            set {
                this.idbodegaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idbodegaSpecified {
            get {
                return this.idbodegaFieldSpecified;
            }
            set {
                this.idbodegaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idcodigo {
            get {
                return this.idcodigoField;
            }
            set {
                this.idcodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idcodigoSpecified {
            get {
                return this.idcodigoFieldSpecified;
            }
            set {
                this.idcodigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int iddocumento {
            get {
                return this.iddocumentoField;
            }
            set {
                this.iddocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iddocumentoSpecified {
            get {
                return this.iddocumentoFieldSpecified;
            }
            set {
                this.iddocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string identidad {
            get {
                return this.identidadField;
            }
            set {
                this.identidadField = value;
            }
        }
        
        /// <remarks/>
        public long idnumero {
            get {
                return this.idnumeroField;
            }
            set {
                this.idnumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idnumeroSpecified {
            get {
                return this.idnumeroFieldSpecified;
            }
            set {
                this.idnumeroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idsucursal {
            get {
                return this.idsucursalField;
            }
            set {
                this.idsucursalField = value;
            }
        }
        
        /// <remarks/>
        public int linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineaSpecified {
            get {
                return this.lineaFieldSpecified;
            }
            set {
                this.lineaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string razon_social {
            get {
                return this.razon_socialField;
            }
            set {
                this.razon_socialField = value;
            }
        }
        
        /// <remarks/>
        public decimal rtu {
            get {
                return this.rtuField;
            }
            set {
                this.rtuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rtuSpecified {
            get {
                return this.rtuFieldSpecified;
            }
            set {
                this.rtuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string simbolo_bodega {
            get {
                return this.simbolo_bodegaField;
            }
            set {
                this.simbolo_bodegaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unidad_primaria {
            get {
                return this.unidad_primariaField;
            }
            set {
                this.unidad_primariaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unidad_secundaria {
            get {
                return this.unidad_secundariaField;
            }
            set {
                this.unidad_secundariaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Get_GuiasCompletedEventHandler(object sender, Get_GuiasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_GuiasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_GuiasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Guias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Guias[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591